# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "has_dynamic_fields"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Ayre"]
  s.date = "2012-04-16"
  s.description = "Lets your models act dynamic in a clean EAV style"
  s.email = "jasonayre@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/generators/dynamic_field_migration_generator.rb",
    "lib/generators/dynamic_field_scaffold_generator.rb",
    "lib/generators/templates/add_field_migration.rb",
    "lib/generators/templates/fieldgroup_model_template.rb",
    "lib/generators/templates/fieldgroups_table_migration.rb",
    "lib/generators/templates/fieldoptions_model_template.rb",
    "lib/generators/templates/fieldoptions_table_migration.rb",
    "lib/generators/templates/fields_model_template.rb",
    "lib/generators/templates/fields_table_migration.rb",
    "lib/generators/templates/fieldvalues_model_template.rb",
    "lib/generators/templates/fieldvalues_table_migration.rb",
    "lib/generators/templates/remove_field_migration.rb",
    "lib/tasks/dynamic_field_migrate.rake",
    "spec/spec_helper.rb",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/jasonayre/has_dynamic_fields"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Lets your models act dynamically in a clean EAV style"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<seed-fu>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<seed-fu>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<seed-fu>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

